# Generated by Django 2.1 on 2018-09-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_tag_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='abbreviation',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
