# Generated by Django 2.1 on 2018-08-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='can_submit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
