# Generated by Django 2.1 on 2018-09-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0003_auto_20180902_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description_length',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
