# Generated by Django 2.1 on 2018-09-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0004_problem_description_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='implement_rating',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='thinking_rating',
            field=models.IntegerField(default=-1),
        ),
    ]
