# Generated by Django 2.1 on 2018-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0006_problem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='parent_contest',
            field=models.ManyToManyField(blank=True, to='boj.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problems.Tag'),
        ),
    ]
