# Generated by Django 2.1 on 2018-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boj', '0007_auto_20180907_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
