# Generated by Django 2.1 on 2018-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.IntegerField()),
                ('problem', models.IntegerField()),
                ('result', models.CharField(max_length=9)),
                ('source', models.CharField(max_length=99999)),
            ],
            options={
                'ordering': ('submission',),
            },
        ),
    ]
