# Generated by Django 2.1 on 2018-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajebiii_boj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default='C++14', max_length=99),
            preserve_default=False,
        ),
    ]
