# Generated by Django 2.1 on 2018-09-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kajebiii_boj', '0002_submission_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='source',
            field=models.TextField(),
        ),
    ]
